version: '3.9'

services:
  frontend:
    container_name: cash_front-dev
    build: 
      context: ./frontend
      dockerfile: dev.Dockerfile
    tty: true
    ports:
      - 3000:8080
    volumes:
      - ./frontend/src:/src
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
      start_period: 30s
  backend:
    container_name: cash_back-dev
    restart: always
    build: ./backend
    tty: true
    command: npm run dev
    ports:
      - 3001:3001
    volumes:
      - ./backend/src:/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      - API_PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - HOST=db
      - DB_PORT=3306
      - DB_NAME=cashforce_v4
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
      start_period: 60s
  db:
    image: mariadb:10-jammy
    container_name: cash_db-dev
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysql" ,"-u", "root", "--password=123456", "-w", "-V"]
      timeout: 10s
      retries: 5
      start_period: 60s
    cap_add:
      - SYS_NICE
networks:
  default:
    name: cashForce-net-dev